### PR TITLE
Better MCI-SendStringA, added missing joyConfigChanged, and small fixes        

### PR DESCRIPTION
**Pull request by rkkoszewski**

### CODE REVIEW

**Comment by bangstk** [comment]
There's a few merge conflicts so I'll have to sort them out first, but I'll merge it. Thanks for adding to the project.

About your 1 track CD fix: does it affect other music playback behaviors? In games playing a sequence of tracks (such as "play from 2 to 4") it is supposed to only play tracks 2 and 3. (The original project and indeed even GoG's own fork does not properly do this, I guess games that play several tracks with one call are fairly rare, Jedi Knight is the only one I can think of that does)

**Comment by rkkoszewski** [comment]
Hi, I tested the fix with Subculture (Uses mciSendCommand) and with Ultim@te Race Pro (Uses mciSendString) both with expected results. But both games usually just play one song. The issue seems to be in the player.

To play just one track, you would have to use "play from 1 to 2" to play just Track 1 as the last track is excluded. You cannot use "play from 1 to 1" as the last track is exclusive and would stop the playback immediately on play.

The problem is when there are for example 2 tracks on disk. In ogg-winmm when you try to play track 99 it defaults to the last track (which is 2). So you cannot use "play from 2 to 3" as 3 would default to 2 getting as result a "play from 2 to 2" which stops playback immediately at play.

An other problem is the TMSF mapping for one track songs.. The time is mapped to the Track number. So in order to play just one song in Ultim@te Race Pro (And probably other games too) it plays the Track 1@0:00 to Track 1@3:45 (3:45 being the last second of the track). Both are mapped to Track 1 and would result in a "play from 1 to 1" again being immediately stopped on play.

I haven't tested my fix with other games that play multiple tracks. But I've been thinking about an other less hacky fix.

As this is mostly a player issue, we could just change the this line from wav-winmm.c from:

```
if (current == last)
            playing = 0;
```

to

```
if (first == last && current > last || first != last && current == last)
            playing = 0;
```

This would have the normal behaviour for tracks who have different first and last track, and have single track behaviour where first equals to the last track.

This way the player should play tracks when the first track equals the last track.
WARNING: I haven't tested this as I don't have much time right now, but it should do the trick. 

Hope it works.
Greetings.

**Comment by rkkoszewski** [comment]
BTW: Add this after
   // POSITION
   if(..){

   }


			// NUMBER
			if (com && strcmp(com, "number") == 0) {
				com = strtok(NULL, " ,.-"); // Get next token
				
				// OF
				if (com && strcmp(com, "of") == 0) {
					com = strtok(NULL, " ,.-"); // Get next token
					
					// TRACKS
					if (com && strcmp(com, "tracks") == 0) {
						itoa(numTracks, ret, 10); // Response
						return 0;
					}	
				}
				
				return 0;
			}

**Comment by rkkoszewski** [comment]
BTW: Add after: 

```
        // POSITION
        if (com && strcmp(com, "position") == 0) {
        ...
        }
```

this:

```
        // NUMBER
        if (com && strcmp(com, "number") == 0) {
            com = strtok(NULL, " ,.-"); // Get next token

            // OF
            if (com && strcmp(com, "of") == 0) {
                com = strtok(NULL, " ,.-"); // Get next token

                // TRACKS
                if (com && strcmp(com, "tracks") == 0) {
                    itoa(numTracks, ret, 10); // Response
                    return 0;
                }   
            }

            return 0;
        }
```

To support "status x number of tracks" to be at par with GMMan modification.

**Comment by bangstk** [comment]
Ok, sorry for letting this go so long as I had exams, I'll get this put in this weekend

**Comment by rkkoszewski** [comment]
I have rebased my fork so it can be automatically merged.
Here is the new pull request:
https://github.com/bangstk/ogg-winmm/pull/3

**Pull request closed without merging**
